Update postinst

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -48,7 +48,7 @@ add_group() {
 
 
 
-cd /opt/gz-siem-collector/ || exit 1
+cd /opt/gz-https2syslog-event-listener/ || exit 1
 
 if hash npm 2> /dev/null; then
           echo "Running 'npm install' dependencies"
@@ -58,13 +58,13 @@ if hash npm 2> /dev/null; then
         echo ""
         echo ""
         echo "WARN: 'npm' was not found. Dependencies may be missing!!!"
-        echo "Manually install npm, and do a "npm install --production --unsafe-perm" in /opt/gz-siem-collector ."
+        echo "Manually install npm, and do a "npm install --production --unsafe-perm" in /opt/gz-https2syslog-event-listener ."
         echo ""
 fi
 
 
 
-if [ ! -f /opt/gz-siem-collector/api/config/config.json ]; then
+if [ ! -f /opt/gz-https2syslog-event-listener/api/config/config.json ]; then
     echo ""
     echo ""
 
@@ -78,10 +78,10 @@ if [ ! -f /opt/gz-siem-collector/api/config/config.json ]; then
 
     cert_pass=$(printf '%s\n' "$cert_pass" | sed -e 's/[]\/$*.^[]/\\&/g');
 
-    sed "s/5678secure5678/$auth_string/" /opt/gz-siem-collector/api/config/config.json.template > /opt/gz-siem-collector/api/config/config.json
-    sed -i "s/1234pass1234/$cert_pass/" /opt/gz-siem-collector/api/config/config.json
+    sed "s/5678secure5678/$auth_string/" /opt/gz-https2syslog-event-listener/api/config/config.json.template > /opt/gz-https2syslog-event-listener/api/config/config.json
+    sed -i "s/1234pass1234/$cert_pass/" /opt/gz-https2syslog-event-listener/api/config/config.json
 else
-    if [ ! -f /opt/gz-siem-collector/certs/ssl.cer ] || [ ! -f /opt/gz-siem-collector/certs/sslkey.pem ]; then
+    if [ ! -f /opt/gz-https2syslog-event-listener/certs/ssl.cer ] || [ ! -f /opt/gz-https2syslog-event-listener/certs/sslkey.pem ]; then
          echo ""
          echo ""
          echo "Found a config.json file in place, but certificates are missing. Regenerating new self signed certificates...."
@@ -91,13 +91,13 @@ else
          openssl req -newkey rsa:2048 -days 365 -x509 -keyout certs/sslkey.pem -out certs/ssl.cer -sha256 -subj "/C=RO/O=BD/CN=DEFAULT_SIEM_COLLECTOR_CERT/" -passout pass:$cert_pass
 
 
-         auth_string="$(jq -r '.authorization_string' /opt/gz-siem-collector/api/config/config.json)"
+         auth_string="$(jq -r '.authorization_string' /opt/gz-https2syslog-event-listener/api/config/config.json)"
          auth_string=$(printf '%s\n' "$auth_string" | sed -e 's/[]\/$*.^[]/\\&/g');
 
          cert_pass=$(printf '%s\n' "$cert_pass" | sed -e 's/[]\/$*.^[]/\\&/g');
 
-         sed "s/Basic\ 5678secure5678/$auth_string/" /opt/gz-siem-collector/api/config/config.json.template > /opt/gz-siem-collector/api/config/config.json
-         sed -i "s/1234pass1234/$cert_pass/" /opt/gz-siem-collector/api/config/config.json
+         sed "s/Basic\ 5678secure5678/$auth_string/" /opt/gz-https2syslog-event-listener/api/config/config.json.template > /opt/gz-https2syslog-event-listener/api/config/config.json
+         sed -i "s/1234pass1234/$cert_pass/" /opt/gz-https2syslog-event-listener/api/config/config.json
     fi
 fi
 
@@ -107,27 +107,27 @@ fi
 add_group 'gzsiemcollector' ''
 add_user 'gzsiemcollector' '' 'gzsiemcollector' 'gzsiemcollector user-daemon' '/bin/false'
 
-chown -R 'gzsiemcollector:gzsiemcollector' '/opt/gz-siem-collector'
+chown -R 'gzsiemcollector:gzsiemcollector' '/opt/gz-https2syslog-event-listener'
 
 echo ""
 echo ""
 
 echo "Enabling and starting gzsiemcollector service....."
 
-if systemctl enable gz-siem-collector.service && systemctl start gz-siem-collector.service; then
-       echo "The gz-siem-collector.service is now installed."
+if systemctl enable gz-https2syslog-event-listener.service && systemctl start gz-https2syslog-event-listener.service; then
+       echo "The gz-https2syslog-event-listener.service is now installed."
 else
-       echo "Failed to activate and/or start gz-siem-collector.service."
+       echo "Failed to activate and/or start gz-https2syslog-event-listener.service."
 fi
 
 echo ""
 echo ""
 echo "#####################################################################################"
-echo "gz-siem-collector  is currently installed using the following configuration settings:"
-jq '.' /opt/gz-siem-collector/api/config/config.json
+echo "gz-https2syslog-event-listener  is currently installed using the following configuration settings:"
+jq '.' /opt/gz-https2syslog-event-listener/api/config/config.json
 echo "#####################################################################################"
 echo "To tailor the configuration to your needs, modify the following configuration file:"
-echo "/opt/gz-siem-collector/api/config/config.json"
+echo "/opt/gz-https2syslog-event-listener/api/config/config.json"
 echo "For more information, please refer to the KB article documenting this tool."
 echo "#####################################################################################"
 echo ""
@@ -135,15 +135,15 @@ echo ""
 echo "#####################################################################################"
 echo ""
 echo "To start stop restart the service, use systemctl. "
-echo "eg. sudo systemctl restart gz-siem-collector"
+echo "eg. sudo systemctl restart gz-https2syslog-event-listener"
 echo ""
-echo "To get the service status: sudo systemctl status gz-siem-collector"
+echo "To get the service status: sudo systemctl status gz-https2syslog-event-listener"
 echo ""
 echo "Always restart the collector service after updating configuration files."
 echo ""
-echo "To inspect the gz-siem-collector service logs, you can use journalctl."
-echo "eg. journalctl -u gz-siem-collector"
-echo "    journalctl -fu gz-siem-collector"
+echo "To inspect the gz-https2syslog-event-listener service logs, you can use journalctl."
+echo "eg. journalctl -u gz-https2syslog-event-listener"
+echo "    journalctl -fu gz-https2syslog-event-listener"
 echo ""
 echo ""
 echo "#####################################################################################"
